spring:
    application:
        name: MentalHealthSystem
    datasource:
        url: jdbc:mysql://localhost:3306/mental_health_system?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
    jackson:
        date-format: yyyy-MM-dd
        time-zone: GMT+8

mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 

server:
  port: 8080
  servlet:
    context-path: /mental 

deepseek:
    api:
        key: ${DEEPSEEK_API_KEY}
