spring:
    application:
        name: BookMangeSystem
    datasource:
        url: jdbc:mysql://localhost:3306/booksystem?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
    jackson:
        date-format: yyyy-MM-dd
        time-zone: GMT+8

mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 